# Generated by Django 4.1 on 2023-02-18 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 6, 2, 54, 107971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 6, 2, 54, 107538, tzinfo=datetime.timezone.utc)),
        ),
    ]
