# Generated by Django 4.1 on 2023-02-18 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 6, 8, 33, 456020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 6, 8, 33, 455578, tzinfo=datetime.timezone.utc)),
        ),
    ]
